version: '3'

services:
  ldap.example.com:
    container_name: ldap
    image: "osixia/openldap:1.5.0"
    env_file:
      - ./.env
    volumes:
      - ./ldap/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command: --copy-service
    ports:
      - 389:389

  log4j:
    container_name: log4j
    image: maven:3.8.3-openjdk-11
    command: mvn compile exec:java -Dexec.mainClass=com.sample.App -f /root/work/rce/pom.xml
    volumes:
      - ./log4j/work:/root/work
    tty: true
    ports:
      - 8081:8081
  
  web.example.com:
    container_name: web
    image: tomcat:jdk11-openjdk
    volumes:
      - ./web/work:/root/work
    command: /root/work/entrypoint.sh
    ports:
      - 8080:8080